import { Topic } from '@/types/chat'

export const TOPICS: Topic[] = [
  {
    id: 'general',
    labelAr: 'عام',
    labelEn: 'General',
    icon: '💬',
    descriptionAr: 'أسئلة عامة في المحاسبة',
    descriptionEn: 'General accounting questions',
    color: 'bg-slate-100 text-slate-700 border-slate-200',
  },
  {
    id: 'zakat',
    labelAr: 'الزكاة',
    labelEn: 'Zakat',
    icon: '🌙',
    descriptionAr: 'احتساب الزكاة والإقرارات',
    descriptionEn: 'Zakat calculation & filing',
    color: 'bg-green-50 text-green-700 border-green-200',
  },
  {
    id: 'vat',
    labelAr: 'ضريبة القيمة المضافة',
    labelEn: 'VAT',
    icon: '🧾',
    descriptionAr: 'ضريبة القيمة المضافة 15%',
    descriptionEn: 'VAT rules & compliance',
    color: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    id: 'ifrs',
    labelAr: 'المعايير الدولية',
    labelEn: 'IFRS',
    icon: '📊',
    descriptionAr: 'معايير IFRS في المملكة',
    descriptionEn: 'IFRS in Saudi Arabia',
    color: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  {
    id: 'auditing',
    labelAr: 'المراجعة',
    labelEn: 'Auditing',
    icon: '🔍',
    descriptionAr: 'معايير المراجعة والتدقيق',
    descriptionEn: 'Auditing standards (ISA)',
    color: 'bg-orange-50 text-orange-700 border-orange-200',
  },
  {
    id: 'corporate-law',
    labelAr: 'نظام الشركات',
    labelEn: 'Companies Law',
    icon: '⚖️',
    descriptionAr: 'نظام الشركات 2022',
    descriptionEn: 'Saudi Companies Law 2022',
    color: 'bg-red-50 text-red-700 border-red-200',
  },
  {
    id: 'e-invoicing',
    labelAr: 'الفوترة الإلكترونية',
    labelEn: 'E-Invoicing',
    icon: '📱',
    descriptionAr: 'فاتورة — المرحلتان 1 و 2',
    descriptionEn: 'Fatoorah Phase 1 & 2',
    color: 'bg-teal-50 text-teal-700 border-teal-200',
  },
  {
    id: 'capital-markets',
    labelAr: 'الأسواق المالية',
    labelEn: 'Capital Markets',
    icon: '📈',
    descriptionAr: 'تداول وهيئة السوق المالية',
    descriptionEn: 'Tadawul & CMA',
    color: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  {
    id: 'banking',
    labelAr: 'القطاع المصرفي',
    labelEn: 'Banking & Insurance',
    icon: '🏦',
    descriptionAr: 'ساما والتمويل الإسلامي',
    descriptionEn: 'SAMA, IFRS 9, Islamic finance',
    color: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  },
  {
    id: 'vision2030',
    labelAr: 'رؤية 2030',
    labelEn: 'Vision 2030',
    icon: '🏗️',
    descriptionAr: 'المشاريع العملاقة والخصخصة',
    descriptionEn: 'Giga-projects & privatization',
    color: 'bg-yellow-50 text-yellow-700 border-yellow-200',
  },
  {
    id: 'government',
    labelAr: 'المحاسبة الحكومية',
    labelEn: 'Government Accounting',
    icon: '🏛️',
    descriptionAr: 'IPSAS والتقارير الحكومية',
    descriptionEn: 'IPSAS & public sector',
    color: 'bg-rose-50 text-rose-700 border-rose-200',
  },
]
